config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :sentences do
    resources :entities
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entity.rb
# frozen_string_literal: true

class Entity < ApplicationRecord
  belongs_to :sentence

  validates :name, :entity_type, presence: true

  validates :name, uniqueness: {
    case_sensitive: false,
    scope: :sentence_id
  }

  validates :name, :entity_type, format: {
    with: /^[#{I18n.t("entity_pattern")}]*$/,
    message: I18n.t('entity_format_message'),
    multiline: true
  }
end

app/models/sentence.rb
# frozen_string_literal: true

class Sentence < ApplicationRecord
  has_many :entities

  validates :content,
            presence: true,
            uniqueness: { case_sensitive: true }
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include ActionView::RecordIdentifier
end

app/controllers/entities_controller.rb
# frozen_string_literal: true

class EntitiesController < ApplicationController
  before_action :set_sentence

  def new
    @entity = @sentence.entities.new
  end

  def create
    @entity = @sentence.entities.create(entity_params)

    if @entity.valid?
      redirect_to sentences_url(page: params[:page]), status: :see_other
    else
      render action: :new, status: 422
    end
  end

  private

  def entity_params
    params.require(:entity).permit(:name, :entity_type)
  end

  def set_sentence
    @sentence = Sentence.find(params[:sentence_id])
  end
end

app/controllers/sentences_controller.rb
# frozen_string_literal: true

class SentencesController < ApplicationController
  include Pagy::Backend
  before_action :set_sentence, except: :index

  def index
    @pagy, @sentences = pagy(Sentence.includes(:entities), page: params[:page])
  end

  def edit; end

  def update
    if @sentence.update(sentence_params)
      redirect_to action: :index, status: :see_other, page: params[:page]
    else
      render action: :edit, status: 422
    end
  end

  private

  def sentence_params
    params.require(:sentence).permit(:content)
  end

  def set_sentence
    @sentence = Sentence.find(params[:id])
  end
end

app/helpers/sentences_helper.rb
# frozen_string_literal: true

module SentencesHelper
  include Pagy::Frontend

  def annotated_content(content, entities)
    tokens = content.split
    annotated_tokens = []

    tokens.each do |token|
      annotated_tokens << token
      entities.each do |entity|
        if token.gsub(/[^#{I18n.t("entity_pattern")}]/, '') == entity.name
          annotated_tokens[-1] = token.gsub(/\b#{entity.name}\b/, annotation_template(entity.name, entity.entity_type))
          break
        end
      end
    end

    annotated_tokens.join(' ')
  end

  def annotation_template(name, entity_type)
    ApplicationController.render(
      partial: 'shared/tag',
      locals: { name:, entity_type: }
    )
  end
end

app/views/entities/new.html.erb
<%= form_for [@sentence, @entity] do |form| %>
  <%= render "shared/page" %>
  <%= render "shared/errors", resource: @entity %>
  
  <div class="input-group mb-3">
    <%= form.text_field :name, class: "form-control", placeholder: I18n.t("name") %>
  </div>

  <div class="input-group mb-3">
    <%= form.text_field :entity_type, class: "form-control", placeholder: I18n.t("type") %>
  </div>

  <div class="input-group mb-3">
    <%= form.submit I18n.t("form.save"), class: "btn btn-primary" %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= I18n.t("heading") %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_pack_tag 'application' %>
    <%= javascript_pack_tag 'application', 'data-turbo-track': 'reload' %>
  </head>

  <body>
    <div class="container mt-5">
      <%= yield %>
    </div>
  </body>
</html>

app/views/sentences/components/_card.html.erb
<div class="card my-5 shadow">
  <div class="card-body">
    <div>
      <% sentence.entities.each do |entity| %>
        <%= render "shared/tag", name: entity.name, entity_type: entity.entity_type %>
      <% end %>
    </div>
    <hr/>

    <div>
      <%== annotated_content(sentence.content, sentence.entities) %>
    </div>
    <hr/>

    <div class="d-flex justify-content-end">
      <%= link_to I18n.t("create_entity"), new_sentence_entity_path(sentence, page: params[:page]), class: "btn btn-primary mx-1" %>
      <%= link_to I18n.t("edit_sentence"), edit_sentence_path(sentence, page: params[:page]), class: "btn btn-primary mx-1" %>
    </div>
  </div>
</div>

app/views/sentences/edit.html.erb
<%= form_for @sentence do |form| %>
  <%= render "shared/page" %>
  <%= render "shared/errors", resource: @sentence %>

  <div class="input-group mb-3">
    <%= form.text_area :content, class: "form-control", rows: 10, cols: 200, placeholder: I18n.t("content") %>
  </div>

  <div class="input-group mb-3">
    <%= form.submit I18n.t("form.save"), class: "btn btn-primary" %>
  </div>
<% end %>

app/views/sentences/index.html.erb
<%= render "shared/heading", heading: I18n.t("heading") %>

<% @sentences.each do |sentence| %>
  <%= render "sentences/components/card", sentence: %>
<% end %>

<%== pagy_bootstrap_nav(@pagy) %>

app/views/shared/_errors.html.erb
<div class="text-danger mb-3">
  <%= resource.errors.full_messages.to_sentence %>
</div>

app/views/shared/_heading.html.erb
<h1 class="my-5">
  <%= heading %>
</h1>

app/views/shared/_page.html.erb
<%= hidden_field_tag :page, params[:page] %>

app/views/shared/_tag.html.erb
<span class="badge text-bg-primary">
  <%= name %>
  <%= entity_type %>
</span>